// Generated by the protocol buffer compiler.  DO NOT EDIT!



@class ErrorReportParams;
@class ErrorReportParams_Builder;
@class MsgApiStatus;
@class MsgApiStatus_Builder;
@class MsgBanner;
@class MsgBanner_Builder;
@class MsgBindResult;
@class MsgBindResult_Builder;
@class MsgBindingAcccount;
@class MsgBindingAcccount_Builder;
@class MsgBoard;
@class MsgBoard_Builder;
@class MsgDish;
@class MsgDish_Builder;
@class MsgDishes;
@class MsgDishes_Builder;
@class MsgDynamicInfo;
@class MsgDynamicInfo_Builder;
@class MsgEditorSelected;
@class MsgEditorSelected_Builder;
@class MsgMoreDetail;
@class MsgMoreDetail_Builder;
@class MsgMoreDetails;
@class MsgMoreDetails_Builder;
@class MsgReasonInfo;
@class MsgReasonInfo_Builder;
@class MsgRelatedRest;
@class MsgRelatedRest_Builder;
@class MsgRestBrief;
@class MsgRestBrief_Builder;
@class MsgRestComment;
@class MsgRestComment_Builder;
@class MsgRestComments;
@class MsgRestComments_Builder;
@class MsgRestDetail;
@class MsgRestDetail_Builder;
@class MsgRestInfo;
@class MsgRestInfo_Builder;
@class MsgRestInfos;
@class MsgRestInfos_Builder;
@class MsgRestRecommend;
@class MsgRestRecommend_Builder;
@class MsgRestUgc;
@class MsgRestUgc_Builder;
@class MsgSelectedCity;
@class MsgSelectedCity_Builder;
@class MsgSuggestion;
@class MsgSuggestion_Builder;
@class MsgSuggestions;
@class MsgSuggestions_Builder;
@class MsgTableData;
@class MsgTableData_Builder;
@class MsgTableRow;
@class MsgTableRow_Builder;
@class MsgTextInfo;
@class MsgTextInfo_Builder;
@class MsgTokenInfo;
@class MsgTokenInfo_Builder;
@class MsgTokenInfos;
@class MsgTokenInfos_Builder;
@class MsgUpdateInfo;
@class MsgUpdateInfo_Builder;
@class MsgUserInfo;
@class MsgUserInfo_Builder;
@class PersonalizeParams;
@class PersonalizeParams_Builder;
@class RecommendParams;
@class RecommendParams_Builder;
@class SuggestParams;
@class SuggestParams_Builder;
typedef enum {
  UpdateStatusInvalid = -1,
  UpdateStatusLatest = 0,
  UpdateStatusOutdated = 1,
  UpdateStatusDiscard = 2,
} UpdateStatus;

BOOL UpdateStatusIsValidValue(UpdateStatus value);

typedef enum {
  TrafficModeInvalidMode = -1,
  TrafficModeWalk = 0,
  TrafficModeBus = 1,
  TrafficModeDrive = 2,
  TrafficModeTrain = 3,
  TrafficModeFly = 4,
} TrafficMode;

BOOL TrafficModeIsValidValue(TrafficMode value);

typedef enum {
  PersonalizeParams_TypeInvalid = -1,
  PersonalizeParams_TypeAll = 0,
  PersonalizeParams_TypeNearby = 1,
  PersonalizeParams_TypeHome = 2,
  PersonalizeParams_TypeCity = 3,
  PersonalizeParams_TypeAreas = 4,
} PersonalizeParams_Type;

BOOL PersonalizeParams_TypeIsValidValue(PersonalizeParams_Type value);

typedef enum {
  RecommendParams_TypeInvalid = -1,
  RecommendParams_TypeNormal = 0,
  RecommendParams_TypeCity = 1,
  RecommendParams_TypeEditor = 2,
  RecommendParams_TypeSearch = 3,
} RecommendParams_Type;

BOOL RecommendParams_TypeIsValidValue(RecommendParams_Type value);

typedef enum {
  RecommendParams_ReasonTypeSimilar = 0,
  RecommendParams_ReasonTypeChain = 1,
  RecommendParams_ReasonTypeChainSimilar = 2,
  RecommendParams_ReasonTypeRegionBoardNear = 3,
  RecommendParams_ReasonTypeRegionBoardArea = 4,
  RecommendParams_ReasonTypeRegionBoardCity = 5,
  RecommendParams_ReasonTypeArtiBoard = 6,
  RecommendParams_ReasonTypeHome = 7,
  RecommendParams_ReasonTypeCube = 8,
  RecommendParams_ReasonTypeWeibo = 9,
  RecommendParams_ReasonTypeEditorRec = 10,
  RecommendParams_ReasonTypeSdish = 11,
  RecommendParams_ReasonTypeRandom = 12,
  RecommendParams_ReasonTypeJingxuan = 13,
  RecommendParams_ReasonTypeSimilarDish = 21,
  RecommendParams_ReasonTypeFavorCurrentDish = 22,
  RecommendParams_ReasonTypeFavorGlobalDish = 23,
  RecommendParams_ReasonTypeSoloDish = 24,
  RecommendParams_ReasonTypeBaseDish = 25,
  RecommendParams_ReasonTypeDislikeDish = 26,
} RecommendParams_ReasonType;

BOOL RecommendParams_ReasonTypeIsValidValue(RecommendParams_ReasonType value);

typedef enum {
  ErrorReportParams_TypeInvalid = -1,
  ErrorReportParams_TypeRestNotExsist = 0,
  ErrorReportParams_TypeRestStyleError = 1,
  ErrorReportParams_TypeRestAddressError = 2,
  ErrorReportParams_TypeRestTelError = 3,
  ErrorReportParams_TypeRestClosed = 4,
  ErrorReportParams_TypeRestOtherError = 9,
  ErrorReportParams_TypeDishNotExsist = 10,
  ErrorReportParams_TypeDishAtError = 11,
  ErrorReportParams_TypeDishOtherError = 15,
} ErrorReportParams_Type;

BOOL ErrorReportParams_TypeIsValidValue(ErrorReportParams_Type value);

typedef enum {
  SuggestParams_TypeInvalid = -1,
  SuggestParams_TypeRestaurant = 0,
  SuggestParams_TypeDish = 1,
} SuggestParams_Type;

BOOL SuggestParams_TypeIsValidValue(SuggestParams_Type value);


@interface SilmarilRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PersonalizeParams : PBGeneratedMessage {
@private
}

+ (PersonalizeParams*) defaultInstance;
- (PersonalizeParams*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PersonalizeParams_Builder*) builder;
+ (PersonalizeParams_Builder*) builder;
+ (PersonalizeParams_Builder*) builderWithPrototype:(PersonalizeParams*) prototype;

+ (PersonalizeParams*) parseFromData:(NSData*) data;
+ (PersonalizeParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PersonalizeParams*) parseFromInputStream:(NSInputStream*) input;
+ (PersonalizeParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PersonalizeParams*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PersonalizeParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PersonalizeParams_Builder : PBGeneratedMessage_Builder {
@private
  PersonalizeParams* result;
}

- (PersonalizeParams*) defaultInstance;

- (PersonalizeParams_Builder*) clear;
- (PersonalizeParams_Builder*) clone;

- (PersonalizeParams*) build;
- (PersonalizeParams*) buildPartial;

- (PersonalizeParams_Builder*) mergeFrom:(PersonalizeParams*) other;
- (PersonalizeParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PersonalizeParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RecommendParams : PBGeneratedMessage {
@private
}

+ (RecommendParams*) defaultInstance;
- (RecommendParams*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RecommendParams_Builder*) builder;
+ (RecommendParams_Builder*) builder;
+ (RecommendParams_Builder*) builderWithPrototype:(RecommendParams*) prototype;

+ (RecommendParams*) parseFromData:(NSData*) data;
+ (RecommendParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RecommendParams*) parseFromInputStream:(NSInputStream*) input;
+ (RecommendParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RecommendParams*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RecommendParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RecommendParams_Builder : PBGeneratedMessage_Builder {
@private
  RecommendParams* result;
}

- (RecommendParams*) defaultInstance;

- (RecommendParams_Builder*) clear;
- (RecommendParams_Builder*) clone;

- (RecommendParams*) build;
- (RecommendParams*) buildPartial;

- (RecommendParams_Builder*) mergeFrom:(RecommendParams*) other;
- (RecommendParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RecommendParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ErrorReportParams : PBGeneratedMessage {
@private
}

+ (ErrorReportParams*) defaultInstance;
- (ErrorReportParams*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ErrorReportParams_Builder*) builder;
+ (ErrorReportParams_Builder*) builder;
+ (ErrorReportParams_Builder*) builderWithPrototype:(ErrorReportParams*) prototype;

+ (ErrorReportParams*) parseFromData:(NSData*) data;
+ (ErrorReportParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ErrorReportParams*) parseFromInputStream:(NSInputStream*) input;
+ (ErrorReportParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ErrorReportParams*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ErrorReportParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ErrorReportParams_Builder : PBGeneratedMessage_Builder {
@private
  ErrorReportParams* result;
}

- (ErrorReportParams*) defaultInstance;

- (ErrorReportParams_Builder*) clear;
- (ErrorReportParams_Builder*) clone;

- (ErrorReportParams*) build;
- (ErrorReportParams*) buildPartial;

- (ErrorReportParams_Builder*) mergeFrom:(ErrorReportParams*) other;
- (ErrorReportParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ErrorReportParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SuggestParams : PBGeneratedMessage {
@private
}

+ (SuggestParams*) defaultInstance;
- (SuggestParams*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SuggestParams_Builder*) builder;
+ (SuggestParams_Builder*) builder;
+ (SuggestParams_Builder*) builderWithPrototype:(SuggestParams*) prototype;

+ (SuggestParams*) parseFromData:(NSData*) data;
+ (SuggestParams*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SuggestParams*) parseFromInputStream:(NSInputStream*) input;
+ (SuggestParams*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SuggestParams*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SuggestParams*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SuggestParams_Builder : PBGeneratedMessage_Builder {
@private
  SuggestParams* result;
}

- (SuggestParams*) defaultInstance;

- (SuggestParams_Builder*) clear;
- (SuggestParams_Builder*) clone;

- (SuggestParams*) build;
- (SuggestParams*) buildPartial;

- (SuggestParams_Builder*) mergeFrom:(SuggestParams*) other;
- (SuggestParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SuggestParams_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgUpdateInfo : PBGeneratedMessage {
@private
  BOOL hasOs_:1;
  BOOL hasLatestversion_:1;
  BOOL hasDownloadurl_:1;
  BOOL hasStatus_:1;
  NSString* os;
  NSString* latestversion;
  NSString* downloadurl;
  UpdateStatus status;
}
- (BOOL) hasStatus;
- (BOOL) hasOs;
- (BOOL) hasLatestversion;
- (BOOL) hasDownloadurl;
@property (readonly) UpdateStatus status;
@property (readonly, retain) NSString* os;
@property (readonly, retain) NSString* latestversion;
@property (readonly, retain) NSString* downloadurl;

+ (MsgUpdateInfo*) defaultInstance;
- (MsgUpdateInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgUpdateInfo_Builder*) builder;
+ (MsgUpdateInfo_Builder*) builder;
+ (MsgUpdateInfo_Builder*) builderWithPrototype:(MsgUpdateInfo*) prototype;

+ (MsgUpdateInfo*) parseFromData:(NSData*) data;
+ (MsgUpdateInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgUpdateInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgUpdateInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgUpdateInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgUpdateInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgUpdateInfo_Builder : PBGeneratedMessage_Builder {
@private
  MsgUpdateInfo* result;
}

- (MsgUpdateInfo*) defaultInstance;

- (MsgUpdateInfo_Builder*) clear;
- (MsgUpdateInfo_Builder*) clone;

- (MsgUpdateInfo*) build;
- (MsgUpdateInfo*) buildPartial;

- (MsgUpdateInfo_Builder*) mergeFrom:(MsgUpdateInfo*) other;
- (MsgUpdateInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgUpdateInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (UpdateStatus) status;
- (MsgUpdateInfo_Builder*) setStatus:(UpdateStatus) value;
- (MsgUpdateInfo_Builder*) clearStatus;

- (BOOL) hasOs;
- (NSString*) os;
- (MsgUpdateInfo_Builder*) setOs:(NSString*) value;
- (MsgUpdateInfo_Builder*) clearOs;

- (BOOL) hasLatestversion;
- (NSString*) latestversion;
- (MsgUpdateInfo_Builder*) setLatestversion:(NSString*) value;
- (MsgUpdateInfo_Builder*) clearLatestversion;

- (BOOL) hasDownloadurl;
- (NSString*) downloadurl;
- (MsgUpdateInfo_Builder*) setDownloadurl:(NSString*) value;
- (MsgUpdateInfo_Builder*) clearDownloadurl;
@end

@interface MsgApiStatus : PBGeneratedMessage {
@private
  BOOL hasCode_:1;
  BOOL hasExecTime_:1;
  BOOL hasMessage_:1;
  BOOL hasDebugInfo_:1;
  int32_t code;
  int32_t execTime;
  NSString* message;
  NSString* debugInfo;
}
- (BOOL) hasCode;
- (BOOL) hasMessage;
- (BOOL) hasExecTime;
- (BOOL) hasDebugInfo;
@property (readonly) int32_t code;
@property (readonly, retain) NSString* message;
@property (readonly) int32_t execTime;
@property (readonly, retain) NSString* debugInfo;

+ (MsgApiStatus*) defaultInstance;
- (MsgApiStatus*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgApiStatus_Builder*) builder;
+ (MsgApiStatus_Builder*) builder;
+ (MsgApiStatus_Builder*) builderWithPrototype:(MsgApiStatus*) prototype;

+ (MsgApiStatus*) parseFromData:(NSData*) data;
+ (MsgApiStatus*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgApiStatus*) parseFromInputStream:(NSInputStream*) input;
+ (MsgApiStatus*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgApiStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgApiStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgApiStatus_Builder : PBGeneratedMessage_Builder {
@private
  MsgApiStatus* result;
}

- (MsgApiStatus*) defaultInstance;

- (MsgApiStatus_Builder*) clear;
- (MsgApiStatus_Builder*) clone;

- (MsgApiStatus*) build;
- (MsgApiStatus*) buildPartial;

- (MsgApiStatus_Builder*) mergeFrom:(MsgApiStatus*) other;
- (MsgApiStatus_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgApiStatus_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCode;
- (int32_t) code;
- (MsgApiStatus_Builder*) setCode:(int32_t) value;
- (MsgApiStatus_Builder*) clearCode;

- (BOOL) hasMessage;
- (NSString*) message;
- (MsgApiStatus_Builder*) setMessage:(NSString*) value;
- (MsgApiStatus_Builder*) clearMessage;

- (BOOL) hasExecTime;
- (int32_t) execTime;
- (MsgApiStatus_Builder*) setExecTime:(int32_t) value;
- (MsgApiStatus_Builder*) clearExecTime;

- (BOOL) hasDebugInfo;
- (NSString*) debugInfo;
- (MsgApiStatus_Builder*) setDebugInfo:(NSString*) value;
- (MsgApiStatus_Builder*) clearDebugInfo;
@end

@interface MsgSuggestions : PBGeneratedMessage {
@private
  PBAppendableArray * suggestionsArray;
}
@property (readonly, retain) PBArray * suggestions;
- (MsgSuggestion*)suggestionsAtIndex:(NSUInteger)index;

+ (MsgSuggestions*) defaultInstance;
- (MsgSuggestions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgSuggestions_Builder*) builder;
+ (MsgSuggestions_Builder*) builder;
+ (MsgSuggestions_Builder*) builderWithPrototype:(MsgSuggestions*) prototype;

+ (MsgSuggestions*) parseFromData:(NSData*) data;
+ (MsgSuggestions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgSuggestions*) parseFromInputStream:(NSInputStream*) input;
+ (MsgSuggestions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgSuggestions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgSuggestions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgSuggestions_Builder : PBGeneratedMessage_Builder {
@private
  MsgSuggestions* result;
}

- (MsgSuggestions*) defaultInstance;

- (MsgSuggestions_Builder*) clear;
- (MsgSuggestions_Builder*) clone;

- (MsgSuggestions*) build;
- (MsgSuggestions*) buildPartial;

- (MsgSuggestions_Builder*) mergeFrom:(MsgSuggestions*) other;
- (MsgSuggestions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgSuggestions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)suggestions;
- (MsgSuggestion*)suggestionsAtIndex:(NSUInteger)index;
- (MsgSuggestions_Builder *)addSuggestions:(MsgSuggestion*)value;
- (MsgSuggestions_Builder *)setSuggestionsArray:(NSArray *)array;
- (MsgSuggestions_Builder *)setSuggestionsValues:(const MsgSuggestion* *)values count:(NSUInteger)count;
- (MsgSuggestions_Builder *)clearSuggestions;
@end

@interface MsgSuggestion : PBGeneratedMessage {
@private
  BOOL hasContent_:1;
  NSString* content;
}
- (BOOL) hasContent;
@property (readonly, retain) NSString* content;

+ (MsgSuggestion*) defaultInstance;
- (MsgSuggestion*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgSuggestion_Builder*) builder;
+ (MsgSuggestion_Builder*) builder;
+ (MsgSuggestion_Builder*) builderWithPrototype:(MsgSuggestion*) prototype;

+ (MsgSuggestion*) parseFromData:(NSData*) data;
+ (MsgSuggestion*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgSuggestion*) parseFromInputStream:(NSInputStream*) input;
+ (MsgSuggestion*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgSuggestion*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgSuggestion*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgSuggestion_Builder : PBGeneratedMessage_Builder {
@private
  MsgSuggestion* result;
}

- (MsgSuggestion*) defaultInstance;

- (MsgSuggestion_Builder*) clear;
- (MsgSuggestion_Builder*) clone;

- (MsgSuggestion*) build;
- (MsgSuggestion*) buildPartial;

- (MsgSuggestion_Builder*) mergeFrom:(MsgSuggestion*) other;
- (MsgSuggestion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgSuggestion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasContent;
- (NSString*) content;
- (MsgSuggestion_Builder*) setContent:(NSString*) value;
- (MsgSuggestion_Builder*) clearContent;
@end

@interface MsgRestBrief : PBGeneratedMessage {
@private
  BOOL hasLongitude_:1;
  BOOL hasLatitude_:1;
  BOOL hasAvgPay_:1;
  BOOL hasSrank_:1;
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasCity_:1;
  BOOL hasStyle_:1;
  BOOL hasAddress_:1;
  Float64 longitude;
  Float64 latitude;
  Float32 avgPay;
  Float32 srank;
  int64_t id;
  NSString* name;
  NSString* city;
  NSString* style;
  NSString* address;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasCity;
- (BOOL) hasStyle;
- (BOOL) hasAddress;
- (BOOL) hasAvgPay;
- (BOOL) hasLongitude;
- (BOOL) hasLatitude;
- (BOOL) hasSrank;
@property (readonly) int64_t id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* city;
@property (readonly, retain) NSString* style;
@property (readonly, retain) NSString* address;
@property (readonly) Float32 avgPay;
@property (readonly) Float64 longitude;
@property (readonly) Float64 latitude;
@property (readonly) Float32 srank;

+ (MsgRestBrief*) defaultInstance;
- (MsgRestBrief*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRestBrief_Builder*) builder;
+ (MsgRestBrief_Builder*) builder;
+ (MsgRestBrief_Builder*) builderWithPrototype:(MsgRestBrief*) prototype;

+ (MsgRestBrief*) parseFromData:(NSData*) data;
+ (MsgRestBrief*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestBrief*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRestBrief*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestBrief*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRestBrief*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRestBrief_Builder : PBGeneratedMessage_Builder {
@private
  MsgRestBrief* result;
}

- (MsgRestBrief*) defaultInstance;

- (MsgRestBrief_Builder*) clear;
- (MsgRestBrief_Builder*) clone;

- (MsgRestBrief*) build;
- (MsgRestBrief*) buildPartial;

- (MsgRestBrief_Builder*) mergeFrom:(MsgRestBrief*) other;
- (MsgRestBrief_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRestBrief_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int64_t) id;
- (MsgRestBrief_Builder*) setId:(int64_t) value;
- (MsgRestBrief_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (MsgRestBrief_Builder*) setName:(NSString*) value;
- (MsgRestBrief_Builder*) clearName;

- (BOOL) hasCity;
- (NSString*) city;
- (MsgRestBrief_Builder*) setCity:(NSString*) value;
- (MsgRestBrief_Builder*) clearCity;

- (BOOL) hasStyle;
- (NSString*) style;
- (MsgRestBrief_Builder*) setStyle:(NSString*) value;
- (MsgRestBrief_Builder*) clearStyle;

- (BOOL) hasAddress;
- (NSString*) address;
- (MsgRestBrief_Builder*) setAddress:(NSString*) value;
- (MsgRestBrief_Builder*) clearAddress;

- (BOOL) hasAvgPay;
- (Float32) avgPay;
- (MsgRestBrief_Builder*) setAvgPay:(Float32) value;
- (MsgRestBrief_Builder*) clearAvgPay;

- (BOOL) hasLongitude;
- (Float64) longitude;
- (MsgRestBrief_Builder*) setLongitude:(Float64) value;
- (MsgRestBrief_Builder*) clearLongitude;

- (BOOL) hasLatitude;
- (Float64) latitude;
- (MsgRestBrief_Builder*) setLatitude:(Float64) value;
- (MsgRestBrief_Builder*) clearLatitude;

- (BOOL) hasSrank;
- (Float32) srank;
- (MsgRestBrief_Builder*) setSrank:(Float32) value;
- (MsgRestBrief_Builder*) clearSrank;
@end

@interface MsgRestDetail : PBGeneratedMessage {
@private
  BOOL hasTel_:1;
  BOOL hasDesc_:1;
  BOOL hasDishes_:1;
  BOOL hasSpecial_:1;
  BOOL hasShophour_:1;
  BOOL hasTraffic_:1;
  BOOL hasSituation_:1;
  BOOL hasImage_:1;
  BOOL hasImagecategory_:1;
  BOOL hasMoredetails_:1;
  NSString* tel;
  NSString* desc;
  NSString* dishes;
  NSString* special;
  NSString* shophour;
  NSString* traffic;
  NSString* situation;
  NSString* image;
  NSString* imagecategory;
  MsgMoreDetails* moredetails;
}
- (BOOL) hasTel;
- (BOOL) hasDesc;
- (BOOL) hasDishes;
- (BOOL) hasSpecial;
- (BOOL) hasShophour;
- (BOOL) hasTraffic;
- (BOOL) hasSituation;
- (BOOL) hasImage;
- (BOOL) hasMoredetails;
- (BOOL) hasImagecategory;
@property (readonly, retain) NSString* tel;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* dishes;
@property (readonly, retain) NSString* special;
@property (readonly, retain) NSString* shophour;
@property (readonly, retain) NSString* traffic;
@property (readonly, retain) NSString* situation;
@property (readonly, retain) NSString* image;
@property (readonly, retain) MsgMoreDetails* moredetails;
@property (readonly, retain) NSString* imagecategory;

+ (MsgRestDetail*) defaultInstance;
- (MsgRestDetail*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRestDetail_Builder*) builder;
+ (MsgRestDetail_Builder*) builder;
+ (MsgRestDetail_Builder*) builderWithPrototype:(MsgRestDetail*) prototype;

+ (MsgRestDetail*) parseFromData:(NSData*) data;
+ (MsgRestDetail*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestDetail*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRestDetail*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestDetail*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRestDetail*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRestDetail_Builder : PBGeneratedMessage_Builder {
@private
  MsgRestDetail* result;
}

- (MsgRestDetail*) defaultInstance;

- (MsgRestDetail_Builder*) clear;
- (MsgRestDetail_Builder*) clone;

- (MsgRestDetail*) build;
- (MsgRestDetail*) buildPartial;

- (MsgRestDetail_Builder*) mergeFrom:(MsgRestDetail*) other;
- (MsgRestDetail_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRestDetail_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTel;
- (NSString*) tel;
- (MsgRestDetail_Builder*) setTel:(NSString*) value;
- (MsgRestDetail_Builder*) clearTel;

- (BOOL) hasDesc;
- (NSString*) desc;
- (MsgRestDetail_Builder*) setDesc:(NSString*) value;
- (MsgRestDetail_Builder*) clearDesc;

- (BOOL) hasDishes;
- (NSString*) dishes;
- (MsgRestDetail_Builder*) setDishes:(NSString*) value;
- (MsgRestDetail_Builder*) clearDishes;

- (BOOL) hasSpecial;
- (NSString*) special;
- (MsgRestDetail_Builder*) setSpecial:(NSString*) value;
- (MsgRestDetail_Builder*) clearSpecial;

- (BOOL) hasShophour;
- (NSString*) shophour;
- (MsgRestDetail_Builder*) setShophour:(NSString*) value;
- (MsgRestDetail_Builder*) clearShophour;

- (BOOL) hasTraffic;
- (NSString*) traffic;
- (MsgRestDetail_Builder*) setTraffic:(NSString*) value;
- (MsgRestDetail_Builder*) clearTraffic;

- (BOOL) hasSituation;
- (NSString*) situation;
- (MsgRestDetail_Builder*) setSituation:(NSString*) value;
- (MsgRestDetail_Builder*) clearSituation;

- (BOOL) hasImage;
- (NSString*) image;
- (MsgRestDetail_Builder*) setImage:(NSString*) value;
- (MsgRestDetail_Builder*) clearImage;

- (BOOL) hasMoredetails;
- (MsgMoreDetails*) moredetails;
- (MsgRestDetail_Builder*) setMoredetails:(MsgMoreDetails*) value;
- (MsgRestDetail_Builder*) setMoredetailsBuilder:(MsgMoreDetails_Builder*) builderForValue;
- (MsgRestDetail_Builder*) mergeMoredetails:(MsgMoreDetails*) value;
- (MsgRestDetail_Builder*) clearMoredetails;

- (BOOL) hasImagecategory;
- (NSString*) imagecategory;
- (MsgRestDetail_Builder*) setImagecategory:(NSString*) value;
- (MsgRestDetail_Builder*) clearImagecategory;
@end

@interface MsgMoreDetails : PBGeneratedMessage {
@private
  PBAppendableArray * detailArray;
}
@property (readonly, retain) PBArray * detail;
- (MsgMoreDetail*)detailAtIndex:(NSUInteger)index;

+ (MsgMoreDetails*) defaultInstance;
- (MsgMoreDetails*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgMoreDetails_Builder*) builder;
+ (MsgMoreDetails_Builder*) builder;
+ (MsgMoreDetails_Builder*) builderWithPrototype:(MsgMoreDetails*) prototype;

+ (MsgMoreDetails*) parseFromData:(NSData*) data;
+ (MsgMoreDetails*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgMoreDetails*) parseFromInputStream:(NSInputStream*) input;
+ (MsgMoreDetails*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgMoreDetails*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgMoreDetails*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgMoreDetails_Builder : PBGeneratedMessage_Builder {
@private
  MsgMoreDetails* result;
}

- (MsgMoreDetails*) defaultInstance;

- (MsgMoreDetails_Builder*) clear;
- (MsgMoreDetails_Builder*) clone;

- (MsgMoreDetails*) build;
- (MsgMoreDetails*) buildPartial;

- (MsgMoreDetails_Builder*) mergeFrom:(MsgMoreDetails*) other;
- (MsgMoreDetails_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgMoreDetails_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)detail;
- (MsgMoreDetail*)detailAtIndex:(NSUInteger)index;
- (MsgMoreDetails_Builder *)addDetail:(MsgMoreDetail*)value;
- (MsgMoreDetails_Builder *)setDetailArray:(NSArray *)array;
- (MsgMoreDetails_Builder *)setDetailValues:(const MsgMoreDetail* *)values count:(NSUInteger)count;
- (MsgMoreDetails_Builder *)clearDetail;
@end

@interface MsgMoreDetail : PBGeneratedMessage {
@private
  BOOL hasLabel_:1;
  BOOL hasPayload_:1;
  NSString* label;
  NSString* payload;
}
- (BOOL) hasLabel;
- (BOOL) hasPayload;
@property (readonly, retain) NSString* label;
@property (readonly, retain) NSString* payload;

+ (MsgMoreDetail*) defaultInstance;
- (MsgMoreDetail*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgMoreDetail_Builder*) builder;
+ (MsgMoreDetail_Builder*) builder;
+ (MsgMoreDetail_Builder*) builderWithPrototype:(MsgMoreDetail*) prototype;

+ (MsgMoreDetail*) parseFromData:(NSData*) data;
+ (MsgMoreDetail*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgMoreDetail*) parseFromInputStream:(NSInputStream*) input;
+ (MsgMoreDetail*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgMoreDetail*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgMoreDetail*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgMoreDetail_Builder : PBGeneratedMessage_Builder {
@private
  MsgMoreDetail* result;
}

- (MsgMoreDetail*) defaultInstance;

- (MsgMoreDetail_Builder*) clear;
- (MsgMoreDetail_Builder*) clone;

- (MsgMoreDetail*) build;
- (MsgMoreDetail*) buildPartial;

- (MsgMoreDetail_Builder*) mergeFrom:(MsgMoreDetail*) other;
- (MsgMoreDetail_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgMoreDetail_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLabel;
- (NSString*) label;
- (MsgMoreDetail_Builder*) setLabel:(NSString*) value;
- (MsgMoreDetail_Builder*) clearLabel;

- (BOOL) hasPayload;
- (NSString*) payload;
- (MsgMoreDetail_Builder*) setPayload:(NSString*) value;
- (MsgMoreDetail_Builder*) clearPayload;
@end

@interface MsgRestUgc : PBGeneratedMessage {
@private
  BOOL hasFavored_:1;
  BOOL hasRate_:1;
  BOOL hasRateTime_:1;
  BOOL hasCommentString_:1;
  BOOL favored_:1;
  Float32 rate;
  int64_t rateTime;
  NSString* commentString;
}
- (BOOL) hasRate;
- (BOOL) hasRateTime;
- (BOOL) hasFavored;
- (BOOL) hasCommentString;
@property (readonly) Float32 rate;
@property (readonly) int64_t rateTime;
- (BOOL) favored;
@property (readonly, retain) NSString* commentString;

+ (MsgRestUgc*) defaultInstance;
- (MsgRestUgc*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRestUgc_Builder*) builder;
+ (MsgRestUgc_Builder*) builder;
+ (MsgRestUgc_Builder*) builderWithPrototype:(MsgRestUgc*) prototype;

+ (MsgRestUgc*) parseFromData:(NSData*) data;
+ (MsgRestUgc*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestUgc*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRestUgc*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestUgc*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRestUgc*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRestUgc_Builder : PBGeneratedMessage_Builder {
@private
  MsgRestUgc* result;
}

- (MsgRestUgc*) defaultInstance;

- (MsgRestUgc_Builder*) clear;
- (MsgRestUgc_Builder*) clone;

- (MsgRestUgc*) build;
- (MsgRestUgc*) buildPartial;

- (MsgRestUgc_Builder*) mergeFrom:(MsgRestUgc*) other;
- (MsgRestUgc_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRestUgc_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRate;
- (Float32) rate;
- (MsgRestUgc_Builder*) setRate:(Float32) value;
- (MsgRestUgc_Builder*) clearRate;

- (BOOL) hasRateTime;
- (int64_t) rateTime;
- (MsgRestUgc_Builder*) setRateTime:(int64_t) value;
- (MsgRestUgc_Builder*) clearRateTime;

- (BOOL) hasFavored;
- (BOOL) favored;
- (MsgRestUgc_Builder*) setFavored:(BOOL) value;
- (MsgRestUgc_Builder*) clearFavored;

- (BOOL) hasCommentString;
- (NSString*) commentString;
- (MsgRestUgc_Builder*) setCommentString:(NSString*) value;
- (MsgRestUgc_Builder*) clearCommentString;
@end

@interface MsgRestRecommend : PBGeneratedMessage {
@private
  BOOL hasDist_:1;
  BOOL hasPredicted_:1;
  BOOL hasRank_:1;
  Float32 dist;
  Float32 predicted;
  Float32 rank;
  PBAppendableArray * reasonsArray;
  PBAppendableArray * reasonInfosArray;
  PBAppendableArray * reasonTypesArray;
}
- (BOOL) hasDist;
- (BOOL) hasPredicted;
- (BOOL) hasRank;
@property (readonly) Float32 dist;
@property (readonly) Float32 predicted;
@property (readonly) Float32 rank;
@property (readonly, retain) PBArray * reasons;
@property (readonly, retain) PBArray * reasonTypes;
@property (readonly, retain) PBArray * reasonInfos;
- (NSString*)reasonsAtIndex:(NSUInteger)index;
- (RecommendParams_ReasonType)reasonTypesAtIndex:(NSUInteger)index;
- (MsgReasonInfo*)reasonInfosAtIndex:(NSUInteger)index;

+ (MsgRestRecommend*) defaultInstance;
- (MsgRestRecommend*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRestRecommend_Builder*) builder;
+ (MsgRestRecommend_Builder*) builder;
+ (MsgRestRecommend_Builder*) builderWithPrototype:(MsgRestRecommend*) prototype;

+ (MsgRestRecommend*) parseFromData:(NSData*) data;
+ (MsgRestRecommend*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestRecommend*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRestRecommend*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestRecommend*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRestRecommend*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRestRecommend_Builder : PBGeneratedMessage_Builder {
@private
  MsgRestRecommend* result;
}

- (MsgRestRecommend*) defaultInstance;

- (MsgRestRecommend_Builder*) clear;
- (MsgRestRecommend_Builder*) clone;

- (MsgRestRecommend*) build;
- (MsgRestRecommend*) buildPartial;

- (MsgRestRecommend_Builder*) mergeFrom:(MsgRestRecommend*) other;
- (MsgRestRecommend_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRestRecommend_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDist;
- (Float32) dist;
- (MsgRestRecommend_Builder*) setDist:(Float32) value;
- (MsgRestRecommend_Builder*) clearDist;

- (BOOL) hasPredicted;
- (Float32) predicted;
- (MsgRestRecommend_Builder*) setPredicted:(Float32) value;
- (MsgRestRecommend_Builder*) clearPredicted;

- (BOOL) hasRank;
- (Float32) rank;
- (MsgRestRecommend_Builder*) setRank:(Float32) value;
- (MsgRestRecommend_Builder*) clearRank;

- (PBAppendableArray *)reasons;
- (NSString*)reasonsAtIndex:(NSUInteger)index;
- (MsgRestRecommend_Builder *)addReasons:(NSString*)value;
- (MsgRestRecommend_Builder *)setReasonsArray:(NSArray *)array;
- (MsgRestRecommend_Builder *)setReasonsValues:(const NSString* *)values count:(NSUInteger)count;
- (MsgRestRecommend_Builder *)clearReasons;

- (PBAppendableArray *)reasonTypes;
- (RecommendParams_ReasonType)reasonTypesAtIndex:(NSUInteger)index;
- (MsgRestRecommend_Builder *)addReasonTypes:(RecommendParams_ReasonType)value;
- (MsgRestRecommend_Builder *)setReasonTypesArray:(NSArray *)array;
- (MsgRestRecommend_Builder *)setReasonTypesValues:(const RecommendParams_ReasonType *)values count:(NSUInteger)count;
- (MsgRestRecommend_Builder *)clearReasonTypes;

- (PBAppendableArray *)reasonInfos;
- (MsgReasonInfo*)reasonInfosAtIndex:(NSUInteger)index;
- (MsgRestRecommend_Builder *)addReasonInfos:(MsgReasonInfo*)value;
- (MsgRestRecommend_Builder *)setReasonInfosArray:(NSArray *)array;
- (MsgRestRecommend_Builder *)setReasonInfosValues:(const MsgReasonInfo* *)values count:(NSUInteger)count;
- (MsgRestRecommend_Builder *)clearReasonInfos;
@end

@interface MsgReasonInfo : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasReason_:1;
  int32_t type;
  NSString* reason;
}
- (BOOL) hasReason;
- (BOOL) hasType;
@property (readonly, retain) NSString* reason;
@property (readonly) int32_t type;

+ (MsgReasonInfo*) defaultInstance;
- (MsgReasonInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgReasonInfo_Builder*) builder;
+ (MsgReasonInfo_Builder*) builder;
+ (MsgReasonInfo_Builder*) builderWithPrototype:(MsgReasonInfo*) prototype;

+ (MsgReasonInfo*) parseFromData:(NSData*) data;
+ (MsgReasonInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgReasonInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgReasonInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgReasonInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgReasonInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgReasonInfo_Builder : PBGeneratedMessage_Builder {
@private
  MsgReasonInfo* result;
}

- (MsgReasonInfo*) defaultInstance;

- (MsgReasonInfo_Builder*) clear;
- (MsgReasonInfo_Builder*) clone;

- (MsgReasonInfo*) build;
- (MsgReasonInfo*) buildPartial;

- (MsgReasonInfo_Builder*) mergeFrom:(MsgReasonInfo*) other;
- (MsgReasonInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgReasonInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasReason;
- (NSString*) reason;
- (MsgReasonInfo_Builder*) setReason:(NSString*) value;
- (MsgReasonInfo_Builder*) clearReason;

- (BOOL) hasType;
- (int32_t) type;
- (MsgReasonInfo_Builder*) setType:(int32_t) value;
- (MsgReasonInfo_Builder*) clearType;
@end

@interface MsgEditorSelected : PBGeneratedMessage {
@private
  BOOL hasDist_:1;
  BOOL hasBatch_:1;
  BOOL hasSelectedText_:1;
  BOOL hasDishes_:1;
  BOOL hasImageType_:1;
  BOOL hasImageUrl_:1;
  BOOL hasTitle_:1;
  BOOL hasDetailText_:1;
  Float32 dist;
  int32_t batch;
  NSString* selectedText;
  NSString* dishes;
  NSString* imageType;
  NSString* imageUrl;
  NSString* title;
  NSString* detailText;
}
- (BOOL) hasDist;
- (BOOL) hasSelectedText;
- (BOOL) hasDishes;
- (BOOL) hasImageType;
- (BOOL) hasImageUrl;
- (BOOL) hasBatch;
- (BOOL) hasTitle;
- (BOOL) hasDetailText;
@property (readonly) Float32 dist;
@property (readonly, retain) NSString* selectedText;
@property (readonly, retain) NSString* dishes;
@property (readonly, retain) NSString* imageType;
@property (readonly, retain) NSString* imageUrl;
@property (readonly) int32_t batch;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* detailText;

+ (MsgEditorSelected*) defaultInstance;
- (MsgEditorSelected*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgEditorSelected_Builder*) builder;
+ (MsgEditorSelected_Builder*) builder;
+ (MsgEditorSelected_Builder*) builderWithPrototype:(MsgEditorSelected*) prototype;

+ (MsgEditorSelected*) parseFromData:(NSData*) data;
+ (MsgEditorSelected*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgEditorSelected*) parseFromInputStream:(NSInputStream*) input;
+ (MsgEditorSelected*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgEditorSelected*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgEditorSelected*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgEditorSelected_Builder : PBGeneratedMessage_Builder {
@private
  MsgEditorSelected* result;
}

- (MsgEditorSelected*) defaultInstance;

- (MsgEditorSelected_Builder*) clear;
- (MsgEditorSelected_Builder*) clone;

- (MsgEditorSelected*) build;
- (MsgEditorSelected*) buildPartial;

- (MsgEditorSelected_Builder*) mergeFrom:(MsgEditorSelected*) other;
- (MsgEditorSelected_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgEditorSelected_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDist;
- (Float32) dist;
- (MsgEditorSelected_Builder*) setDist:(Float32) value;
- (MsgEditorSelected_Builder*) clearDist;

- (BOOL) hasSelectedText;
- (NSString*) selectedText;
- (MsgEditorSelected_Builder*) setSelectedText:(NSString*) value;
- (MsgEditorSelected_Builder*) clearSelectedText;

- (BOOL) hasDishes;
- (NSString*) dishes;
- (MsgEditorSelected_Builder*) setDishes:(NSString*) value;
- (MsgEditorSelected_Builder*) clearDishes;

- (BOOL) hasImageType;
- (NSString*) imageType;
- (MsgEditorSelected_Builder*) setImageType:(NSString*) value;
- (MsgEditorSelected_Builder*) clearImageType;

- (BOOL) hasImageUrl;
- (NSString*) imageUrl;
- (MsgEditorSelected_Builder*) setImageUrl:(NSString*) value;
- (MsgEditorSelected_Builder*) clearImageUrl;

- (BOOL) hasBatch;
- (int32_t) batch;
- (MsgEditorSelected_Builder*) setBatch:(int32_t) value;
- (MsgEditorSelected_Builder*) clearBatch;

- (BOOL) hasTitle;
- (NSString*) title;
- (MsgEditorSelected_Builder*) setTitle:(NSString*) value;
- (MsgEditorSelected_Builder*) clearTitle;

- (BOOL) hasDetailText;
- (NSString*) detailText;
- (MsgEditorSelected_Builder*) setDetailText:(NSString*) value;
- (MsgEditorSelected_Builder*) clearDetailText;
@end

@interface MsgRestInfo : PBGeneratedMessage {
@private
  BOOL hasBrief_:1;
  BOOL hasDetail_:1;
  BOOL hasUgc_:1;
  BOOL hasRec_:1;
  BOOL hasSelected_:1;
  MsgRestBrief* brief;
  MsgRestDetail* detail;
  MsgRestUgc* ugc;
  MsgRestRecommend* rec;
  MsgEditorSelected* selected;
  PBAppendableArray * dishesArray;
}
- (BOOL) hasBrief;
- (BOOL) hasDetail;
- (BOOL) hasUgc;
- (BOOL) hasRec;
- (BOOL) hasSelected;
@property (readonly, retain) MsgRestBrief* brief;
@property (readonly, retain) MsgRestDetail* detail;
@property (readonly, retain) MsgRestUgc* ugc;
@property (readonly, retain) MsgRestRecommend* rec;
@property (readonly, retain) PBArray * dishes;
@property (readonly, retain) MsgEditorSelected* selected;
- (MsgDish*)dishesAtIndex:(NSUInteger)index;

+ (MsgRestInfo*) defaultInstance;
- (MsgRestInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRestInfo_Builder*) builder;
+ (MsgRestInfo_Builder*) builder;
+ (MsgRestInfo_Builder*) builderWithPrototype:(MsgRestInfo*) prototype;

+ (MsgRestInfo*) parseFromData:(NSData*) data;
+ (MsgRestInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRestInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRestInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRestInfo_Builder : PBGeneratedMessage_Builder {
@private
  MsgRestInfo* result;
}

- (MsgRestInfo*) defaultInstance;

- (MsgRestInfo_Builder*) clear;
- (MsgRestInfo_Builder*) clone;

- (MsgRestInfo*) build;
- (MsgRestInfo*) buildPartial;

- (MsgRestInfo_Builder*) mergeFrom:(MsgRestInfo*) other;
- (MsgRestInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRestInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBrief;
- (MsgRestBrief*) brief;
- (MsgRestInfo_Builder*) setBrief:(MsgRestBrief*) value;
- (MsgRestInfo_Builder*) setBriefBuilder:(MsgRestBrief_Builder*) builderForValue;
- (MsgRestInfo_Builder*) mergeBrief:(MsgRestBrief*) value;
- (MsgRestInfo_Builder*) clearBrief;

- (BOOL) hasDetail;
- (MsgRestDetail*) detail;
- (MsgRestInfo_Builder*) setDetail:(MsgRestDetail*) value;
- (MsgRestInfo_Builder*) setDetailBuilder:(MsgRestDetail_Builder*) builderForValue;
- (MsgRestInfo_Builder*) mergeDetail:(MsgRestDetail*) value;
- (MsgRestInfo_Builder*) clearDetail;

- (BOOL) hasUgc;
- (MsgRestUgc*) ugc;
- (MsgRestInfo_Builder*) setUgc:(MsgRestUgc*) value;
- (MsgRestInfo_Builder*) setUgcBuilder:(MsgRestUgc_Builder*) builderForValue;
- (MsgRestInfo_Builder*) mergeUgc:(MsgRestUgc*) value;
- (MsgRestInfo_Builder*) clearUgc;

- (BOOL) hasRec;
- (MsgRestRecommend*) rec;
- (MsgRestInfo_Builder*) setRec:(MsgRestRecommend*) value;
- (MsgRestInfo_Builder*) setRecBuilder:(MsgRestRecommend_Builder*) builderForValue;
- (MsgRestInfo_Builder*) mergeRec:(MsgRestRecommend*) value;
- (MsgRestInfo_Builder*) clearRec;

- (PBAppendableArray *)dishes;
- (MsgDish*)dishesAtIndex:(NSUInteger)index;
- (MsgRestInfo_Builder *)addDishes:(MsgDish*)value;
- (MsgRestInfo_Builder *)setDishesArray:(NSArray *)array;
- (MsgRestInfo_Builder *)setDishesValues:(const MsgDish* *)values count:(NSUInteger)count;
- (MsgRestInfo_Builder *)clearDishes;

- (BOOL) hasSelected;
- (MsgEditorSelected*) selected;
- (MsgRestInfo_Builder*) setSelected:(MsgEditorSelected*) value;
- (MsgRestInfo_Builder*) setSelectedBuilder:(MsgEditorSelected_Builder*) builderForValue;
- (MsgRestInfo_Builder*) mergeSelected:(MsgEditorSelected*) value;
- (MsgRestInfo_Builder*) clearSelected;
@end

@interface MsgRestInfos : PBGeneratedMessage {
@private
  PBAppendableArray * restsArray;
}
@property (readonly, retain) PBArray * rests;
- (MsgRestInfo*)restsAtIndex:(NSUInteger)index;

+ (MsgRestInfos*) defaultInstance;
- (MsgRestInfos*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRestInfos_Builder*) builder;
+ (MsgRestInfos_Builder*) builder;
+ (MsgRestInfos_Builder*) builderWithPrototype:(MsgRestInfos*) prototype;

+ (MsgRestInfos*) parseFromData:(NSData*) data;
+ (MsgRestInfos*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestInfos*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRestInfos*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestInfos*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRestInfos*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRestInfos_Builder : PBGeneratedMessage_Builder {
@private
  MsgRestInfos* result;
}

- (MsgRestInfos*) defaultInstance;

- (MsgRestInfos_Builder*) clear;
- (MsgRestInfos_Builder*) clone;

- (MsgRestInfos*) build;
- (MsgRestInfos*) buildPartial;

- (MsgRestInfos_Builder*) mergeFrom:(MsgRestInfos*) other;
- (MsgRestInfos_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRestInfos_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)rests;
- (MsgRestInfo*)restsAtIndex:(NSUInteger)index;
- (MsgRestInfos_Builder *)addRests:(MsgRestInfo*)value;
- (MsgRestInfos_Builder *)setRestsArray:(NSArray *)array;
- (MsgRestInfos_Builder *)setRestsValues:(const MsgRestInfo* *)values count:(NSUInteger)count;
- (MsgRestInfos_Builder *)clearRests;
@end

@interface MsgRestComment : PBGeneratedMessage {
@private
  BOOL hasRate_:1;
  BOOL hasAvgPay_:1;
  BOOL hasCommentId_:1;
  BOOL hasRestaurantId_:1;
  BOOL hasUserId_:1;
  BOOL hasUserImage_:1;
  BOOL hasTime_:1;
  BOOL hasUserName_:1;
  BOOL hasContent_:1;
  Float32 rate;
  Float32 avgPay;
  int64_t commentId;
  int64_t restaurantId;
  int64_t userId;
  int64_t userImage;
  int64_t time;
  NSString* userName;
  NSString* content;
}
- (BOOL) hasCommentId;
- (BOOL) hasRestaurantId;
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasUserImage;
- (BOOL) hasContent;
- (BOOL) hasRate;
- (BOOL) hasTime;
- (BOOL) hasAvgPay;
@property (readonly) int64_t commentId;
@property (readonly) int64_t restaurantId;
@property (readonly) int64_t userId;
@property (readonly, retain) NSString* userName;
@property (readonly) int64_t userImage;
@property (readonly, retain) NSString* content;
@property (readonly) Float32 rate;
@property (readonly) int64_t time;
@property (readonly) Float32 avgPay;

+ (MsgRestComment*) defaultInstance;
- (MsgRestComment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRestComment_Builder*) builder;
+ (MsgRestComment_Builder*) builder;
+ (MsgRestComment_Builder*) builderWithPrototype:(MsgRestComment*) prototype;

+ (MsgRestComment*) parseFromData:(NSData*) data;
+ (MsgRestComment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestComment*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRestComment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestComment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRestComment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRestComment_Builder : PBGeneratedMessage_Builder {
@private
  MsgRestComment* result;
}

- (MsgRestComment*) defaultInstance;

- (MsgRestComment_Builder*) clear;
- (MsgRestComment_Builder*) clone;

- (MsgRestComment*) build;
- (MsgRestComment*) buildPartial;

- (MsgRestComment_Builder*) mergeFrom:(MsgRestComment*) other;
- (MsgRestComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRestComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCommentId;
- (int64_t) commentId;
- (MsgRestComment_Builder*) setCommentId:(int64_t) value;
- (MsgRestComment_Builder*) clearCommentId;

- (BOOL) hasRestaurantId;
- (int64_t) restaurantId;
- (MsgRestComment_Builder*) setRestaurantId:(int64_t) value;
- (MsgRestComment_Builder*) clearRestaurantId;

- (BOOL) hasUserId;
- (int64_t) userId;
- (MsgRestComment_Builder*) setUserId:(int64_t) value;
- (MsgRestComment_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (MsgRestComment_Builder*) setUserName:(NSString*) value;
- (MsgRestComment_Builder*) clearUserName;

- (BOOL) hasUserImage;
- (int64_t) userImage;
- (MsgRestComment_Builder*) setUserImage:(int64_t) value;
- (MsgRestComment_Builder*) clearUserImage;

- (BOOL) hasContent;
- (NSString*) content;
- (MsgRestComment_Builder*) setContent:(NSString*) value;
- (MsgRestComment_Builder*) clearContent;

- (BOOL) hasRate;
- (Float32) rate;
- (MsgRestComment_Builder*) setRate:(Float32) value;
- (MsgRestComment_Builder*) clearRate;

- (BOOL) hasTime;
- (int64_t) time;
- (MsgRestComment_Builder*) setTime:(int64_t) value;
- (MsgRestComment_Builder*) clearTime;

- (BOOL) hasAvgPay;
- (Float32) avgPay;
- (MsgRestComment_Builder*) setAvgPay:(Float32) value;
- (MsgRestComment_Builder*) clearAvgPay;
@end

@interface MsgRestComments : PBGeneratedMessage {
@private
  PBAppendableArray * commentsArray;
}
@property (readonly, retain) PBArray * comments;
- (MsgRestComment*)commentsAtIndex:(NSUInteger)index;

+ (MsgRestComments*) defaultInstance;
- (MsgRestComments*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRestComments_Builder*) builder;
+ (MsgRestComments_Builder*) builder;
+ (MsgRestComments_Builder*) builderWithPrototype:(MsgRestComments*) prototype;

+ (MsgRestComments*) parseFromData:(NSData*) data;
+ (MsgRestComments*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestComments*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRestComments*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRestComments*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRestComments*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRestComments_Builder : PBGeneratedMessage_Builder {
@private
  MsgRestComments* result;
}

- (MsgRestComments*) defaultInstance;

- (MsgRestComments_Builder*) clear;
- (MsgRestComments_Builder*) clone;

- (MsgRestComments*) build;
- (MsgRestComments*) buildPartial;

- (MsgRestComments_Builder*) mergeFrom:(MsgRestComments*) other;
- (MsgRestComments_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRestComments_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)comments;
- (MsgRestComment*)commentsAtIndex:(NSUInteger)index;
- (MsgRestComments_Builder *)addComments:(MsgRestComment*)value;
- (MsgRestComments_Builder *)setCommentsArray:(NSArray *)array;
- (MsgRestComments_Builder *)setCommentsValues:(const MsgRestComment* *)values count:(NSUInteger)count;
- (MsgRestComments_Builder *)clearComments;
@end

@interface MsgBindingAcccount : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasId_:1;
  int32_t type;
  NSString* id;
}
- (BOOL) hasType;
- (BOOL) hasId;
@property (readonly) int32_t type;
@property (readonly, retain) NSString* id;

+ (MsgBindingAcccount*) defaultInstance;
- (MsgBindingAcccount*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgBindingAcccount_Builder*) builder;
+ (MsgBindingAcccount_Builder*) builder;
+ (MsgBindingAcccount_Builder*) builderWithPrototype:(MsgBindingAcccount*) prototype;

+ (MsgBindingAcccount*) parseFromData:(NSData*) data;
+ (MsgBindingAcccount*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgBindingAcccount*) parseFromInputStream:(NSInputStream*) input;
+ (MsgBindingAcccount*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgBindingAcccount*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgBindingAcccount*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgBindingAcccount_Builder : PBGeneratedMessage_Builder {
@private
  MsgBindingAcccount* result;
}

- (MsgBindingAcccount*) defaultInstance;

- (MsgBindingAcccount_Builder*) clear;
- (MsgBindingAcccount_Builder*) clone;

- (MsgBindingAcccount*) build;
- (MsgBindingAcccount*) buildPartial;

- (MsgBindingAcccount_Builder*) mergeFrom:(MsgBindingAcccount*) other;
- (MsgBindingAcccount_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgBindingAcccount_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (int32_t) type;
- (MsgBindingAcccount_Builder*) setType:(int32_t) value;
- (MsgBindingAcccount_Builder*) clearType;

- (BOOL) hasId;
- (NSString*) id;
- (MsgBindingAcccount_Builder*) setId:(NSString*) value;
- (MsgBindingAcccount_Builder*) clearId;
@end

@interface MsgUserInfo : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasCreateTime_:1;
  BOOL hasRatecount_:1;
  BOOL hasFavorcount_:1;
  BOOL hasName_:1;
  BOOL hasHome_:1;
  BOOL hasCompany_:1;
  BOOL hasTrafficMode_:1;
  int64_t id;
  int64_t createTime;
  int32_t ratecount;
  int32_t favorcount;
  NSString* name;
  NSString* home;
  NSString* company;
  TrafficMode trafficMode;
  PBAppendableArray * areasArray;
  PBAppendableArray * bindingsArray;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasCreateTime;
- (BOOL) hasHome;
- (BOOL) hasCompany;
- (BOOL) hasTrafficMode;
- (BOOL) hasRatecount;
- (BOOL) hasFavorcount;
@property (readonly) int64_t id;
@property (readonly, retain) NSString* name;
@property (readonly) int64_t createTime;
@property (readonly, retain) PBArray * bindings;
@property (readonly, retain) NSString* home;
@property (readonly, retain) NSString* company;
@property (readonly) TrafficMode trafficMode;
@property (readonly, retain) PBArray * areas;
@property (readonly) int32_t ratecount;
@property (readonly) int32_t favorcount;
- (MsgBindingAcccount*)bindingsAtIndex:(NSUInteger)index;
- (NSString*)areasAtIndex:(NSUInteger)index;

+ (MsgUserInfo*) defaultInstance;
- (MsgUserInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgUserInfo_Builder*) builder;
+ (MsgUserInfo_Builder*) builder;
+ (MsgUserInfo_Builder*) builderWithPrototype:(MsgUserInfo*) prototype;

+ (MsgUserInfo*) parseFromData:(NSData*) data;
+ (MsgUserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgUserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgUserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgUserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgUserInfo_Builder : PBGeneratedMessage_Builder {
@private
  MsgUserInfo* result;
}

- (MsgUserInfo*) defaultInstance;

- (MsgUserInfo_Builder*) clear;
- (MsgUserInfo_Builder*) clone;

- (MsgUserInfo*) build;
- (MsgUserInfo*) buildPartial;

- (MsgUserInfo_Builder*) mergeFrom:(MsgUserInfo*) other;
- (MsgUserInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgUserInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int64_t) id;
- (MsgUserInfo_Builder*) setId:(int64_t) value;
- (MsgUserInfo_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (MsgUserInfo_Builder*) setName:(NSString*) value;
- (MsgUserInfo_Builder*) clearName;

- (BOOL) hasCreateTime;
- (int64_t) createTime;
- (MsgUserInfo_Builder*) setCreateTime:(int64_t) value;
- (MsgUserInfo_Builder*) clearCreateTime;

- (PBAppendableArray *)bindings;
- (MsgBindingAcccount*)bindingsAtIndex:(NSUInteger)index;
- (MsgUserInfo_Builder *)addBindings:(MsgBindingAcccount*)value;
- (MsgUserInfo_Builder *)setBindingsArray:(NSArray *)array;
- (MsgUserInfo_Builder *)setBindingsValues:(const MsgBindingAcccount* *)values count:(NSUInteger)count;
- (MsgUserInfo_Builder *)clearBindings;

- (BOOL) hasHome;
- (NSString*) home;
- (MsgUserInfo_Builder*) setHome:(NSString*) value;
- (MsgUserInfo_Builder*) clearHome;

- (BOOL) hasCompany;
- (NSString*) company;
- (MsgUserInfo_Builder*) setCompany:(NSString*) value;
- (MsgUserInfo_Builder*) clearCompany;

- (BOOL) hasTrafficMode;
- (TrafficMode) trafficMode;
- (MsgUserInfo_Builder*) setTrafficMode:(TrafficMode) value;
- (MsgUserInfo_Builder*) clearTrafficMode;

- (PBAppendableArray *)areas;
- (NSString*)areasAtIndex:(NSUInteger)index;
- (MsgUserInfo_Builder *)addAreas:(NSString*)value;
- (MsgUserInfo_Builder *)setAreasArray:(NSArray *)array;
- (MsgUserInfo_Builder *)setAreasValues:(const NSString* *)values count:(NSUInteger)count;
- (MsgUserInfo_Builder *)clearAreas;

- (BOOL) hasRatecount;
- (int32_t) ratecount;
- (MsgUserInfo_Builder*) setRatecount:(int32_t) value;
- (MsgUserInfo_Builder*) clearRatecount;

- (BOOL) hasFavorcount;
- (int32_t) favorcount;
- (MsgUserInfo_Builder*) setFavorcount:(int32_t) value;
- (MsgUserInfo_Builder*) clearFavorcount;
@end

@interface MsgBindResult : PBGeneratedMessage {
@private
  BOOL hasExtra_:1;
  BOOL hasUser_:1;
  NSString* extra;
  MsgUserInfo* user;
}
- (BOOL) hasUser;
- (BOOL) hasExtra;
@property (readonly, retain) MsgUserInfo* user;
@property (readonly, retain) NSString* extra;

+ (MsgBindResult*) defaultInstance;
- (MsgBindResult*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgBindResult_Builder*) builder;
+ (MsgBindResult_Builder*) builder;
+ (MsgBindResult_Builder*) builderWithPrototype:(MsgBindResult*) prototype;

+ (MsgBindResult*) parseFromData:(NSData*) data;
+ (MsgBindResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgBindResult*) parseFromInputStream:(NSInputStream*) input;
+ (MsgBindResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgBindResult*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgBindResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgBindResult_Builder : PBGeneratedMessage_Builder {
@private
  MsgBindResult* result;
}

- (MsgBindResult*) defaultInstance;

- (MsgBindResult_Builder*) clear;
- (MsgBindResult_Builder*) clone;

- (MsgBindResult*) build;
- (MsgBindResult*) buildPartial;

- (MsgBindResult_Builder*) mergeFrom:(MsgBindResult*) other;
- (MsgBindResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgBindResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUser;
- (MsgUserInfo*) user;
- (MsgBindResult_Builder*) setUser:(MsgUserInfo*) value;
- (MsgBindResult_Builder*) setUserBuilder:(MsgUserInfo_Builder*) builderForValue;
- (MsgBindResult_Builder*) mergeUser:(MsgUserInfo*) value;
- (MsgBindResult_Builder*) clearUser;

- (BOOL) hasExtra;
- (NSString*) extra;
- (MsgBindResult_Builder*) setExtra:(NSString*) value;
- (MsgBindResult_Builder*) clearExtra;
@end

@interface MsgBoard : PBGeneratedMessage {
@private
  PBAppendableArray * itemsArray;
}
@property (readonly, retain) PBArray * items;
- (NSString*)itemsAtIndex:(NSUInteger)index;

+ (MsgBoard*) defaultInstance;
- (MsgBoard*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgBoard_Builder*) builder;
+ (MsgBoard_Builder*) builder;
+ (MsgBoard_Builder*) builderWithPrototype:(MsgBoard*) prototype;

+ (MsgBoard*) parseFromData:(NSData*) data;
+ (MsgBoard*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgBoard*) parseFromInputStream:(NSInputStream*) input;
+ (MsgBoard*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgBoard*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgBoard*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgBoard_Builder : PBGeneratedMessage_Builder {
@private
  MsgBoard* result;
}

- (MsgBoard*) defaultInstance;

- (MsgBoard_Builder*) clear;
- (MsgBoard_Builder*) clone;

- (MsgBoard*) build;
- (MsgBoard*) buildPartial;

- (MsgBoard_Builder*) mergeFrom:(MsgBoard*) other;
- (MsgBoard_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgBoard_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)items;
- (NSString*)itemsAtIndex:(NSUInteger)index;
- (MsgBoard_Builder *)addItems:(NSString*)value;
- (MsgBoard_Builder *)setItemsArray:(NSArray *)array;
- (MsgBoard_Builder *)setItemsValues:(const NSString* *)values count:(NSUInteger)count;
- (MsgBoard_Builder *)clearItems;
@end

@interface MsgDishes : PBGeneratedMessage {
@private
  PBAppendableArray * dishesArray;
}
@property (readonly, retain) PBArray * dishes;
- (MsgDish*)dishesAtIndex:(NSUInteger)index;

+ (MsgDishes*) defaultInstance;
- (MsgDishes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgDishes_Builder*) builder;
+ (MsgDishes_Builder*) builder;
+ (MsgDishes_Builder*) builderWithPrototype:(MsgDishes*) prototype;

+ (MsgDishes*) parseFromData:(NSData*) data;
+ (MsgDishes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgDishes*) parseFromInputStream:(NSInputStream*) input;
+ (MsgDishes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgDishes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgDishes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgDishes_Builder : PBGeneratedMessage_Builder {
@private
  MsgDishes* result;
}

- (MsgDishes*) defaultInstance;

- (MsgDishes_Builder*) clear;
- (MsgDishes_Builder*) clone;

- (MsgDishes*) build;
- (MsgDishes*) buildPartial;

- (MsgDishes_Builder*) mergeFrom:(MsgDishes*) other;
- (MsgDishes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgDishes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)dishes;
- (MsgDish*)dishesAtIndex:(NSUInteger)index;
- (MsgDishes_Builder *)addDishes:(MsgDish*)value;
- (MsgDishes_Builder *)setDishesArray:(NSArray *)array;
- (MsgDishes_Builder *)setDishesValues:(const MsgDish* *)values count:(NSUInteger)count;
- (MsgDishes_Builder *)clearDishes;
@end

@interface MsgDish : PBGeneratedMessage {
@private
  BOOL hasPredicted_:1;
  BOOL hasRank_:1;
  BOOL hasCorrelation_:1;
  BOOL hasRate_:1;
  BOOL hasCofreq_:1;
  BOOL hasName_:1;
  BOOL hasRestaurant_:1;
  BOOL hasDetail_:1;
  Float64 predicted;
  Float64 rank;
  Float64 correlation;
  Float32 rate;
  int64_t cofreq;
  NSString* name;
  NSString* restaurant;
  NSString* detail;
  PBAppendableArray * reasonsArray;
}
- (BOOL) hasName;
- (BOOL) hasRestaurant;
- (BOOL) hasRate;
- (BOOL) hasCofreq;
- (BOOL) hasPredicted;
- (BOOL) hasRank;
- (BOOL) hasCorrelation;
- (BOOL) hasDetail;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* restaurant;
@property (readonly, retain) PBArray * reasons;
@property (readonly) Float32 rate;
@property (readonly) int64_t cofreq;
@property (readonly) Float64 predicted;
@property (readonly) Float64 rank;
@property (readonly) Float64 correlation;
@property (readonly, retain) NSString* detail;
- (NSString*)reasonsAtIndex:(NSUInteger)index;

+ (MsgDish*) defaultInstance;
- (MsgDish*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgDish_Builder*) builder;
+ (MsgDish_Builder*) builder;
+ (MsgDish_Builder*) builderWithPrototype:(MsgDish*) prototype;

+ (MsgDish*) parseFromData:(NSData*) data;
+ (MsgDish*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgDish*) parseFromInputStream:(NSInputStream*) input;
+ (MsgDish*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgDish*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgDish*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgDish_Builder : PBGeneratedMessage_Builder {
@private
  MsgDish* result;
}

- (MsgDish*) defaultInstance;

- (MsgDish_Builder*) clear;
- (MsgDish_Builder*) clone;

- (MsgDish*) build;
- (MsgDish*) buildPartial;

- (MsgDish_Builder*) mergeFrom:(MsgDish*) other;
- (MsgDish_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgDish_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (MsgDish_Builder*) setName:(NSString*) value;
- (MsgDish_Builder*) clearName;

- (BOOL) hasRestaurant;
- (NSString*) restaurant;
- (MsgDish_Builder*) setRestaurant:(NSString*) value;
- (MsgDish_Builder*) clearRestaurant;

- (PBAppendableArray *)reasons;
- (NSString*)reasonsAtIndex:(NSUInteger)index;
- (MsgDish_Builder *)addReasons:(NSString*)value;
- (MsgDish_Builder *)setReasonsArray:(NSArray *)array;
- (MsgDish_Builder *)setReasonsValues:(const NSString* *)values count:(NSUInteger)count;
- (MsgDish_Builder *)clearReasons;

- (BOOL) hasRate;
- (Float32) rate;
- (MsgDish_Builder*) setRate:(Float32) value;
- (MsgDish_Builder*) clearRate;

- (BOOL) hasCofreq;
- (int64_t) cofreq;
- (MsgDish_Builder*) setCofreq:(int64_t) value;
- (MsgDish_Builder*) clearCofreq;

- (BOOL) hasPredicted;
- (Float64) predicted;
- (MsgDish_Builder*) setPredicted:(Float64) value;
- (MsgDish_Builder*) clearPredicted;

- (BOOL) hasRank;
- (Float64) rank;
- (MsgDish_Builder*) setRank:(Float64) value;
- (MsgDish_Builder*) clearRank;

- (BOOL) hasCorrelation;
- (Float64) correlation;
- (MsgDish_Builder*) setCorrelation:(Float64) value;
- (MsgDish_Builder*) clearCorrelation;

- (BOOL) hasDetail;
- (NSString*) detail;
- (MsgDish_Builder*) setDetail:(NSString*) value;
- (MsgDish_Builder*) clearDetail;
@end

@interface MsgRelatedRest : PBGeneratedMessage {
@private
  PBAppendableArray * restaurantArray;
}
@property (readonly, retain) PBArray * restaurant;
- (NSString*)restaurantAtIndex:(NSUInteger)index;

+ (MsgRelatedRest*) defaultInstance;
- (MsgRelatedRest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgRelatedRest_Builder*) builder;
+ (MsgRelatedRest_Builder*) builder;
+ (MsgRelatedRest_Builder*) builderWithPrototype:(MsgRelatedRest*) prototype;

+ (MsgRelatedRest*) parseFromData:(NSData*) data;
+ (MsgRelatedRest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRelatedRest*) parseFromInputStream:(NSInputStream*) input;
+ (MsgRelatedRest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgRelatedRest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgRelatedRest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgRelatedRest_Builder : PBGeneratedMessage_Builder {
@private
  MsgRelatedRest* result;
}

- (MsgRelatedRest*) defaultInstance;

- (MsgRelatedRest_Builder*) clear;
- (MsgRelatedRest_Builder*) clone;

- (MsgRelatedRest*) build;
- (MsgRelatedRest*) buildPartial;

- (MsgRelatedRest_Builder*) mergeFrom:(MsgRelatedRest*) other;
- (MsgRelatedRest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgRelatedRest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)restaurant;
- (NSString*)restaurantAtIndex:(NSUInteger)index;
- (MsgRelatedRest_Builder *)addRestaurant:(NSString*)value;
- (MsgRelatedRest_Builder *)setRestaurantArray:(NSArray *)array;
- (MsgRelatedRest_Builder *)setRestaurantValues:(const NSString* *)values count:(NSUInteger)count;
- (MsgRelatedRest_Builder *)clearRestaurant;
@end

@interface MsgBanner : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasTitle_:1;
  BOOL hasDesc_:1;
  BOOL hasImageUrl_:1;
  BOOL hasUrl_:1;
  BOOL hasTarget_:1;
  NSString* id;
  NSString* title;
  NSString* desc;
  NSString* imageUrl;
  NSString* url;
  NSString* target;
}
- (BOOL) hasId;
- (BOOL) hasTitle;
- (BOOL) hasDesc;
- (BOOL) hasImageUrl;
- (BOOL) hasUrl;
- (BOOL) hasTarget;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* desc;
@property (readonly, retain) NSString* imageUrl;
@property (readonly, retain) NSString* url;
@property (readonly, retain) NSString* target;

+ (MsgBanner*) defaultInstance;
- (MsgBanner*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgBanner_Builder*) builder;
+ (MsgBanner_Builder*) builder;
+ (MsgBanner_Builder*) builderWithPrototype:(MsgBanner*) prototype;

+ (MsgBanner*) parseFromData:(NSData*) data;
+ (MsgBanner*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgBanner*) parseFromInputStream:(NSInputStream*) input;
+ (MsgBanner*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgBanner*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgBanner*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgBanner_Builder : PBGeneratedMessage_Builder {
@private
  MsgBanner* result;
}

- (MsgBanner*) defaultInstance;

- (MsgBanner_Builder*) clear;
- (MsgBanner_Builder*) clone;

- (MsgBanner*) build;
- (MsgBanner*) buildPartial;

- (MsgBanner_Builder*) mergeFrom:(MsgBanner*) other;
- (MsgBanner_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgBanner_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MsgBanner_Builder*) setId:(NSString*) value;
- (MsgBanner_Builder*) clearId;

- (BOOL) hasTitle;
- (NSString*) title;
- (MsgBanner_Builder*) setTitle:(NSString*) value;
- (MsgBanner_Builder*) clearTitle;

- (BOOL) hasDesc;
- (NSString*) desc;
- (MsgBanner_Builder*) setDesc:(NSString*) value;
- (MsgBanner_Builder*) clearDesc;

- (BOOL) hasImageUrl;
- (NSString*) imageUrl;
- (MsgBanner_Builder*) setImageUrl:(NSString*) value;
- (MsgBanner_Builder*) clearImageUrl;

- (BOOL) hasUrl;
- (NSString*) url;
- (MsgBanner_Builder*) setUrl:(NSString*) value;
- (MsgBanner_Builder*) clearUrl;

- (BOOL) hasTarget;
- (NSString*) target;
- (MsgBanner_Builder*) setTarget:(NSString*) value;
- (MsgBanner_Builder*) clearTarget;
@end

@interface MsgTableData : PBGeneratedMessage {
@private
  BOOL hasTableName_:1;
  NSString* tableName;
  PBAppendableArray * fieldNamesArray;
  PBAppendableArray * rowsArray;
}
- (BOOL) hasTableName;
@property (readonly, retain) NSString* tableName;
@property (readonly, retain) PBArray * fieldNames;
@property (readonly, retain) PBArray * rows;
- (NSString*)fieldNamesAtIndex:(NSUInteger)index;
- (MsgTableRow*)rowsAtIndex:(NSUInteger)index;

+ (MsgTableData*) defaultInstance;
- (MsgTableData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgTableData_Builder*) builder;
+ (MsgTableData_Builder*) builder;
+ (MsgTableData_Builder*) builderWithPrototype:(MsgTableData*) prototype;

+ (MsgTableData*) parseFromData:(NSData*) data;
+ (MsgTableData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTableData*) parseFromInputStream:(NSInputStream*) input;
+ (MsgTableData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTableData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgTableData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgTableData_Builder : PBGeneratedMessage_Builder {
@private
  MsgTableData* result;
}

- (MsgTableData*) defaultInstance;

- (MsgTableData_Builder*) clear;
- (MsgTableData_Builder*) clone;

- (MsgTableData*) build;
- (MsgTableData*) buildPartial;

- (MsgTableData_Builder*) mergeFrom:(MsgTableData*) other;
- (MsgTableData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgTableData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTableName;
- (NSString*) tableName;
- (MsgTableData_Builder*) setTableName:(NSString*) value;
- (MsgTableData_Builder*) clearTableName;

- (PBAppendableArray *)fieldNames;
- (NSString*)fieldNamesAtIndex:(NSUInteger)index;
- (MsgTableData_Builder *)addFieldNames:(NSString*)value;
- (MsgTableData_Builder *)setFieldNamesArray:(NSArray *)array;
- (MsgTableData_Builder *)setFieldNamesValues:(const NSString* *)values count:(NSUInteger)count;
- (MsgTableData_Builder *)clearFieldNames;

- (PBAppendableArray *)rows;
- (MsgTableRow*)rowsAtIndex:(NSUInteger)index;
- (MsgTableData_Builder *)addRows:(MsgTableRow*)value;
- (MsgTableData_Builder *)setRowsArray:(NSArray *)array;
- (MsgTableData_Builder *)setRowsValues:(const MsgTableRow* *)values count:(NSUInteger)count;
- (MsgTableData_Builder *)clearRows;
@end

@interface MsgTableRow : PBGeneratedMessage {
@private
  PBAppendableArray * fieldValuesArray;
}
@property (readonly, retain) PBArray * fieldValues;
- (NSString*)fieldValuesAtIndex:(NSUInteger)index;

+ (MsgTableRow*) defaultInstance;
- (MsgTableRow*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgTableRow_Builder*) builder;
+ (MsgTableRow_Builder*) builder;
+ (MsgTableRow_Builder*) builderWithPrototype:(MsgTableRow*) prototype;

+ (MsgTableRow*) parseFromData:(NSData*) data;
+ (MsgTableRow*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTableRow*) parseFromInputStream:(NSInputStream*) input;
+ (MsgTableRow*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTableRow*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgTableRow*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgTableRow_Builder : PBGeneratedMessage_Builder {
@private
  MsgTableRow* result;
}

- (MsgTableRow*) defaultInstance;

- (MsgTableRow_Builder*) clear;
- (MsgTableRow_Builder*) clone;

- (MsgTableRow*) build;
- (MsgTableRow*) buildPartial;

- (MsgTableRow_Builder*) mergeFrom:(MsgTableRow*) other;
- (MsgTableRow_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgTableRow_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)fieldValues;
- (NSString*)fieldValuesAtIndex:(NSUInteger)index;
- (MsgTableRow_Builder *)addFieldValues:(NSString*)value;
- (MsgTableRow_Builder *)setFieldValuesArray:(NSArray *)array;
- (MsgTableRow_Builder *)setFieldValuesValues:(const NSString* *)values count:(NSUInteger)count;
- (MsgTableRow_Builder *)clearFieldValues;
@end

@interface MsgTextInfo : PBGeneratedMessage {
@private
  BOOL hasText_:1;
  NSString* text;
}
- (BOOL) hasText;
@property (readonly, retain) NSString* text;

+ (MsgTextInfo*) defaultInstance;
- (MsgTextInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgTextInfo_Builder*) builder;
+ (MsgTextInfo_Builder*) builder;
+ (MsgTextInfo_Builder*) builderWithPrototype:(MsgTextInfo*) prototype;

+ (MsgTextInfo*) parseFromData:(NSData*) data;
+ (MsgTextInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTextInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgTextInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTextInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgTextInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgTextInfo_Builder : PBGeneratedMessage_Builder {
@private
  MsgTextInfo* result;
}

- (MsgTextInfo*) defaultInstance;

- (MsgTextInfo_Builder*) clear;
- (MsgTextInfo_Builder*) clone;

- (MsgTextInfo*) build;
- (MsgTextInfo*) buildPartial;

- (MsgTextInfo_Builder*) mergeFrom:(MsgTextInfo*) other;
- (MsgTextInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgTextInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasText;
- (NSString*) text;
- (MsgTextInfo_Builder*) setText:(NSString*) value;
- (MsgTextInfo_Builder*) clearText;
@end

@interface MsgTokenInfos : PBGeneratedMessage {
@private
  PBAppendableArray * tokensArray;
}
@property (readonly, retain) PBArray * tokens;
- (MsgTokenInfo*)tokensAtIndex:(NSUInteger)index;

+ (MsgTokenInfos*) defaultInstance;
- (MsgTokenInfos*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgTokenInfos_Builder*) builder;
+ (MsgTokenInfos_Builder*) builder;
+ (MsgTokenInfos_Builder*) builderWithPrototype:(MsgTokenInfos*) prototype;

+ (MsgTokenInfos*) parseFromData:(NSData*) data;
+ (MsgTokenInfos*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTokenInfos*) parseFromInputStream:(NSInputStream*) input;
+ (MsgTokenInfos*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTokenInfos*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgTokenInfos*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgTokenInfos_Builder : PBGeneratedMessage_Builder {
@private
  MsgTokenInfos* result;
}

- (MsgTokenInfos*) defaultInstance;

- (MsgTokenInfos_Builder*) clear;
- (MsgTokenInfos_Builder*) clone;

- (MsgTokenInfos*) build;
- (MsgTokenInfos*) buildPartial;

- (MsgTokenInfos_Builder*) mergeFrom:(MsgTokenInfos*) other;
- (MsgTokenInfos_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgTokenInfos_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)tokens;
- (MsgTokenInfo*)tokensAtIndex:(NSUInteger)index;
- (MsgTokenInfos_Builder *)addTokens:(MsgTokenInfo*)value;
- (MsgTokenInfos_Builder *)setTokensArray:(NSArray *)array;
- (MsgTokenInfos_Builder *)setTokensValues:(const MsgTokenInfo* *)values count:(NSUInteger)count;
- (MsgTokenInfos_Builder *)clearTokens;
@end

@interface MsgTokenInfo : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasToken_:1;
  int64_t userId;
  NSString* token;
}
- (BOOL) hasUserId;
- (BOOL) hasToken;
@property (readonly) int64_t userId;
@property (readonly, retain) NSString* token;

+ (MsgTokenInfo*) defaultInstance;
- (MsgTokenInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgTokenInfo_Builder*) builder;
+ (MsgTokenInfo_Builder*) builder;
+ (MsgTokenInfo_Builder*) builderWithPrototype:(MsgTokenInfo*) prototype;

+ (MsgTokenInfo*) parseFromData:(NSData*) data;
+ (MsgTokenInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTokenInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgTokenInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgTokenInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgTokenInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgTokenInfo_Builder : PBGeneratedMessage_Builder {
@private
  MsgTokenInfo* result;
}

- (MsgTokenInfo*) defaultInstance;

- (MsgTokenInfo_Builder*) clear;
- (MsgTokenInfo_Builder*) clone;

- (MsgTokenInfo*) build;
- (MsgTokenInfo*) buildPartial;

- (MsgTokenInfo_Builder*) mergeFrom:(MsgTokenInfo*) other;
- (MsgTokenInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgTokenInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int64_t) userId;
- (MsgTokenInfo_Builder*) setUserId:(int64_t) value;
- (MsgTokenInfo_Builder*) clearUserId;

- (BOOL) hasToken;
- (NSString*) token;
- (MsgTokenInfo_Builder*) setToken:(NSString*) value;
- (MsgTokenInfo_Builder*) clearToken;
@end

@interface MsgDynamicInfo : PBGeneratedMessage {
@private
  PBAppendableArray * selectedCitysArray;
}
@property (readonly, retain) PBArray * selectedCitys;
- (MsgSelectedCity*)selectedCitysAtIndex:(NSUInteger)index;

+ (MsgDynamicInfo*) defaultInstance;
- (MsgDynamicInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgDynamicInfo_Builder*) builder;
+ (MsgDynamicInfo_Builder*) builder;
+ (MsgDynamicInfo_Builder*) builderWithPrototype:(MsgDynamicInfo*) prototype;

+ (MsgDynamicInfo*) parseFromData:(NSData*) data;
+ (MsgDynamicInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgDynamicInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgDynamicInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgDynamicInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgDynamicInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgDynamicInfo_Builder : PBGeneratedMessage_Builder {
@private
  MsgDynamicInfo* result;
}

- (MsgDynamicInfo*) defaultInstance;

- (MsgDynamicInfo_Builder*) clear;
- (MsgDynamicInfo_Builder*) clone;

- (MsgDynamicInfo*) build;
- (MsgDynamicInfo*) buildPartial;

- (MsgDynamicInfo_Builder*) mergeFrom:(MsgDynamicInfo*) other;
- (MsgDynamicInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgDynamicInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)selectedCitys;
- (MsgSelectedCity*)selectedCitysAtIndex:(NSUInteger)index;
- (MsgDynamicInfo_Builder *)addSelectedCitys:(MsgSelectedCity*)value;
- (MsgDynamicInfo_Builder *)setSelectedCitysArray:(NSArray *)array;
- (MsgDynamicInfo_Builder *)setSelectedCitysValues:(const MsgSelectedCity* *)values count:(NSUInteger)count;
- (MsgDynamicInfo_Builder *)clearSelectedCitys;
@end

@interface MsgSelectedCity : PBGeneratedMessage {
@private
  BOOL hasStatus_:1;
  BOOL hasLen_:1;
  BOOL hasCity_:1;
  BOOL status_:1;
  int32_t len;
  NSString* city;
}
- (BOOL) hasCity;
- (BOOL) hasStatus;
- (BOOL) hasLen;
@property (readonly, retain) NSString* city;
- (BOOL) status;
@property (readonly) int32_t len;

+ (MsgSelectedCity*) defaultInstance;
- (MsgSelectedCity*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgSelectedCity_Builder*) builder;
+ (MsgSelectedCity_Builder*) builder;
+ (MsgSelectedCity_Builder*) builderWithPrototype:(MsgSelectedCity*) prototype;

+ (MsgSelectedCity*) parseFromData:(NSData*) data;
+ (MsgSelectedCity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgSelectedCity*) parseFromInputStream:(NSInputStream*) input;
+ (MsgSelectedCity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgSelectedCity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgSelectedCity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgSelectedCity_Builder : PBGeneratedMessage_Builder {
@private
  MsgSelectedCity* result;
}

- (MsgSelectedCity*) defaultInstance;

- (MsgSelectedCity_Builder*) clear;
- (MsgSelectedCity_Builder*) clone;

- (MsgSelectedCity*) build;
- (MsgSelectedCity*) buildPartial;

- (MsgSelectedCity_Builder*) mergeFrom:(MsgSelectedCity*) other;
- (MsgSelectedCity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgSelectedCity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCity;
- (NSString*) city;
- (MsgSelectedCity_Builder*) setCity:(NSString*) value;
- (MsgSelectedCity_Builder*) clearCity;

- (BOOL) hasStatus;
- (BOOL) status;
- (MsgSelectedCity_Builder*) setStatus:(BOOL) value;
- (MsgSelectedCity_Builder*) clearStatus;

- (BOOL) hasLen;
- (int32_t) len;
- (MsgSelectedCity_Builder*) setLen:(int32_t) value;
- (MsgSelectedCity_Builder*) clearLen;
@end

